### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by WaleedAshraf**
I have updated the readme to only consider articles submitted by the project. Also, I think we should move the maintenance of the medium@nodejs.org email and Medium account under the Node.js Social Team. Though, If the team doesn't agree on this, I'll update the PR as we decide.

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
Tagging some of the reviewers of the publication. cc @joesepi @mhdawson @MylesBorins @Trott

**Review by Trott — APPROVED** [review]
Changes look good to me, although honestly, I think we should shut this down. Let's focus on the communication channels that are actively maintained and effective. I don't think trying to reinvigorate the Medium channel, which was always problematic anyway, is a good use of anyone's time at this point.

**Comment by mhdawson** [comment]
I agree with @Trott that we need input from @bnb and @joesepi as I'm think I've heard people say that Medium is not something we are planning to use going forward.

**Comment by WaleedAshraf** [comment]
Node.js Collection initiative was kind of left out when we retired CommComm, and we didn't make any final/concrete decision on it.

These are the accounts we have on Medium

- Node.js Collection Publication: https://medium.com/the-node-js-collection
- Node.js user account: https://nodejs.medium.com/
- Email: medium@nodejs.org (I'm on this alias, not sure who/how many more people we have)
- 18 people have **Editor** access to Node.js Collection Publication
- 39 people have **Writer** access to Node.js Collection Publication

One option is that we completely remove this initiative. If we agree on it, then I suggest clearing up everything. Deactivate both accounts and the Email alias. This way there will no maintenance will be required from anyone.

Another option is putting it under some team (social-team seems most suitable) only as maintenance mode. No publications from the public and use it only for Node.js Project announcements/reach out. For example the last article for "[Help Wanted: Node Addon API’s Road to Full Unit Test Coverage](https://medium.com/the-node-js-collection/help-wanted-node-addon-apis-road-to-full-unit-test-coverage-1d3dbef8f7ab)". Even with this approach, I want to clean up the access for **Writers** and **Editors** and the Email alias and only keep it to limited people.

I'm personally in favor of the second option, but also fine with the first if we decide so.

@Trott @mhdawson I agree on taking input from @bnb and @joesepi. Will convert this PR to a draft.

**Comment by WaleedAshraf** [comment]
Moved the discussion to issue: https://github.com/nodejs/nodejs-collection/issues/44

**Comment by Trott** [comment]
Going to close this and update the README to say this initiative is archived.

**Pull request closed without merging**
