### PR TITLE
Added links to popular blog posts

### PR DESCRIPTION
**Pull request by trivikr**

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by trivikr** [comment]
@mhdawson This PR should be good to merge.

**Comment by WaleedAshraf** [comment]
@trivikr on what base these posts were selected?
I see a lot of other posts with more claps and shares (if that counts), like: 

- https://medium.com/the-node-js-collection/modernizing-node-js-with-idiomatic-javascript-f18d984dcf93
- https://medium.com/the-node-js-collection/the-current-state-of-implementation-and-planning-for-esmodules-a4ecb2aac07a

I think, at that time (when this doc was created), these posts were most popular but not now.

**Comment by trivikr** [comment]
@WaleedAshraf I've just added the links to popular posts mentioned in the `README.md` and didn't check the new popular posts.

**Comment by WaleedAshraf** [comment]
Yes, agree with that. This is not within the scope of PR. LGTM
But maybe we need to update the posts.

**Comment by trivikr** [comment]
ping

**Review by WaleedAshraf — APPROVED** [review]

**Comment by trivikr** [comment]
Closing as this PR have been dormant for more than a year

**Pull request closed without merging**
