### PR TITLE
small edit and embedded link to Node.js Collection

### PR DESCRIPTION
**Pull request by gtewallace**
changed text in first line from "Node.js Collective" to Node.js Collection" and embedded link to the Collection so visitors can see what it's all about

### CODE REVIEW

**Comment by gtewallace** [comment]
@bnb @Trott 
hi both - quick ping to see if one of you may be able to help get this merged.
please lmk if I've missed a step or if you have any questions.
Thank you

**Comment by Trott** [comment]
@nodejs/nodejs-collection Can someone either merge this or advise on process?

**Comment by nebrius** [comment]
The typical workflow for landing PRs looks something like this:

- The PR is open for at least 48 hours to give people a chance to take a look.
- At least one member signs off on the PR by using the "Approve" review feature
- Someone other than the PR author clicks the merge button
    - In smaller teams such as this one, this step can be onerous. I informally use the rule that if the last approval was more than 24 hours ago for one of my own PRs, then I'll merge it myself if it seems like no one else is going to.

EDIT: all that said, you are free to come up with your own rules!

**Comment by bnb** [comment]
Going to close this, since it looks like the change has already been landed in master 👍

**Pull request closed without merging**
